version: '2.4'
services:
  backend:
    image: api-tipo-cambio:latest
    build:
      context: .
    volumes:
      - ./docker-files/application.yml:/opt/application.yml
    ports:
      - "9091:9091"
    depends_on:
      - db
  db:
    image: mcmoe/mssqldocker
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: sa
      MSSQL_DB: 'RetoBd'
      MSSQL_USER: sa
      MSSQL_PASSWORD: sa
    ports:
      - "1433:1433"

